### ISSUE TITLE
Problemas para iniciar la aplicación

### ISSUE THREAD

**Issue by lazki** [HuayraLinux/HuayraDuino-LR#4]
Hola!

Siguiendo las instrucciones del README.md no pude lanzar la aplicación. Parece que está hardcodeada la ubicación.

Saludos!

**Comment by danielferro69** [comment]
> Hola!
> 
> Siguiendo las instrucciones del README.md no pude lanzar la aplicación. Parece que está hardcodeada la ubicación.
> 
> Saludos!

Hola, 

Gracias por el contacto.
Si, es cierto, ha quedado desactualizado el readme.
Ya lo actualizaremos.

Mientras tanto, la aplicacion se puede ejecutar desde /usr/bin/huayra-duino-lr

al mismo tiempo, si la ejecutaras desde el codigo, debes primero instalar las dependencias con
npm install

y luego ejecutar 

npm start

tambien si estas usando debian o ubuntu dependiendo de cada uno, podes generar los paquetes .deb y .rpm ejecutando 
npm run make

te dejará los paquetes de instalacion en out/make/deb/x64

cualquier cosa, nos escribis

Saludos
